---
theme: jekyll-theme-dinky
title: Comment se faire accidenter en toute sécurité ?
image: /Voiture.jpg 
---

defaults:
  # Posts defaults
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts # Apply the default values below only to posts
    values:
      image: /Voiture.jpg 
